# Generated by Django 4.0.2 on 2025-04-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.moviesession'),
        ),
    ]
